
log_file_dir = "local/logs"
data_dir = "local/data"
download_data = true

[dataset]
data_id = "yellow_tripdata"
timestamp_column = "tpep_pickup_datetime"
urls = [
    "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-01.parquet",
    "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-02.parquet",
    "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-03.parquet"
]